/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jcon.si.incremental.app;

import org.junit.jupiter.api.Test;

import java.util.concurrent.TimeUnit;

import static org.junit.jupiter.api.Assertions.assertEquals;

class MessageUtilsTest {

    private static final long TEN_SECONDS_IN_MILLIS = TimeUnit.SECONDS.toMillis(10);

    @Test
    void testGetMessage() throws InterruptedException {
        Thread.sleep(TEN_SECONDS_IN_MILLIS);

        System.out.println("Hello JCon!");
        System.out.println("Bla");
        assertEquals("Hello      World!", MessageUtils.getMessage());
    }
}